name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the Ubuntu runner for Kali Linux

    steps:
      - name: Set up QEMU/KVM
        uses: helmuthva/kvm-qemu-action@v1

      - name: Download Kali Linux image
        run: |
          curl -o kali-linux.qcow2 https://images.kali.org/virtual-images/kali-linux-2021.3-vm-amd64.7z
          7z x kali-linux.qcow2.7z
          sudo mv kali-linux.qcow2 /var/lib/libvirt/images/

      - name: Start Kali Linux VM
        run: |
          sudo virt-install \
            --name kali-linux \
            --ram 4096 \
            --disk /var/lib/libvirt/images/kali-linux.qcow2 \
            --import \
            --os-variant debian10 \
            --network network=default

      - name: Wait for VM to start
        run: sleep 60  # You can adjust the wait time as needed

      - name: Install and configure xrdp
        run: |
          sudo apt update
          sudo apt install -y xrdp
          sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini  # Change the default RDP port to 3390
          sudo systemctl restart xrdp

      - name: Install ngrok
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip

      - name: Auth ngrok
        run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create Tunnel
        run: ./ngrok tcp 3390  # Use the same port as configured for xrdp

      # Add more steps here if needed
