authtoken: 2TCqBqbMntraUqTbL8E4YSpN3kG_45pz87dC2sfoVArSmVuMj
tunnels:
  rdp1:
    proto: tcp
    addr: 3389
  rdp2:
    proto: tcp
    addr: 3390
  rdp3:
    proto: tcp
    addr: 3391
  # Add more tunnels as needed
